FROM docker.io/library/gcc:13-bookworm

ENV JAVA_HOME=/opt/java/openjdk
COPY --from=eclipse-temurin:8 $JAVA_HOME $JAVA_HOME
ENV PATH="${JAVA_HOME}/bin:${PATH}"

RUN apt update && apt install -y flex bison cmake maven ant && apt-get clean
